package com.mentit.mento.domain.users.constant;


public enum UserJob {
   SERVICE_PLAN, BRAND_MARKETING, GROSS_MARKETING, UI_UX_DESIGN, BRAND_DESIGN, MARKETING_WEB_DESIGN,
    BACKEND, FRONTEND, WEB_DEVELOPER, APP_DEVELOPER, AI_DEVELOPER, PROMPTER, DATA_MANAGEMENT_DEVELOPER

}
