spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/mentoapp
      port: 27017
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mentoapp?serverTimezone=Asia/Seoul
    username: root
    password: Group0000-

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: zVYnRQcs6r4ZBlkUVlZi
            client-secret: __Ranu5PEO
            authorization_grant_type: authorization_code
            scope:
              - name
              - nickname
              - email
              - gender
              - profile_image
              - mobile
              - birthyear
              - brithday
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: da5ea2155aaebc8e268669008de949d6
            client-secret: u3HHPiI7tDyRug9tcFhaAopIynpufPxp
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
              - name
              - gender
              - phone_number
              - birthyear
              - birthday
            client-name: Kakao

        provider:

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true


social:
  revoke:
    kakaoUrl: https://kapi.kakao.com/v1/user/unlink
    naverUrl: https://nid.naver.com/oauth2.0/token
    googleUrl: https://oauth2.googleapis.com/revoke




jwt:
  secret: aowieurlwkj12309dfusoirm20394u123sdfasdlfkui2d02kd783
  #1시간
  token:
    access-token-expiration-time: 3600000
    #2주
    refresh-token-expiration-time: 1209600000



springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    doc-expansion: none
